BM25_PATH = "/media/Z/NDT/IR/one_stage/bm25"
WIKI_PATH = "/media/Z/NDT/IR/dataset/wiki/wikipedia_20220620_cleaned_v5.csv"
TEST_PATH = "/media/Z/NDT/IR/dataset/test/test_ir.csv"
WEIGHT_MODEL = "/media/Z/NDT/IR/one_stage_with_ranking/training/weight/best_f1.bin"
MODEL_NAME = "nguyenvulebinh/vi-mrc-base"